attach_book:
  description_size: 500
author:
  name_size: 200
  description_size: 500
book:
  title_size: 200
  description_size: 500
  image_size: 500
category:
  name_size: 200
  description_size: 500
comment:
  content_size: 500
publisher:
  name_size: 200
  address_size: 200
  email_size: 100
  phone_size: 20
  description_size: 500
request:
  description_size: 500
review:
  content_size: 500
user:
  name_size: 200
  phone_size: 20
  password_digest_size: 500
  email_size: 100
  address_size: 200
  avatar_size: 200
categories:
  per_page: 10
  params_page: 1
users_controllers:
  per_page: 10
categories_edit_form:
  per_rows: 4
